# Generated by Django 5.0.2 on 2024-02-22 05:40

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+254798556797', max_length=30, region=None, verbose_name='Phone number'),
        ),
    ]
