version: '3.8'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn order_system.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
      
  db:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - "5432:5433"
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  postgres:
