services:
  api:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    image: gcr.io/savannah-test/order-management-api:latest
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  postgres:
