version: '3.8'
services:
  api:
    build: ./app
    image: order-management-system-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery
  db:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env.db
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
  celery:
    build: ./app
    command: celery -A order_managemnt worker --loglevel=INFO
    volumes:
      - ./app:/usr/src/app/
    depends_on:
      - redis
      - db

volumes:
  postgres:
