# Generated by Django 5.0.2 on 2024-02-19 16:52

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(inventory.models.get_default_category), related_name='product_list', to='inventory.category'),
        ),
    ]
