apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-management-api
  template:
    metadata:
      labels:
        app: order-management-api
    spec:
      containers:
      - name: order-management-api
        image: order-management-api:latest
        ports:
        - containerPort: 8000


