apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-management-api
  template:
    metadata:
      labels:
        app: order-management-api
    spec:
      containers:
      - name: order-management-api
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: api-secret
        - configMapRef:
            name: db-config
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 0.5
            memory: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-management-api-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: order-management-api-service
            port:
              number: 80
